### ISSUE TITLE
Allow wildcards for ignoring dependencies

### ISSUE THREAD

**Issue by westy92** [alanshaw/david#135]
It would be nice to be able to ignore `['@types/*']` instead of listing them: `['@types/lodash', '@types/moment']`.

**Comment by jpaulin** [comment]
@westy92 
Very nice idea. I'm prepping to work on this, because I think it could be made along with another idea. [The other one is about adding '^' caret support for the version range.] 

Just thinking what kind of use cases would be sane to include at this point. 
a) '*' just using asterisk in JavaScript -manner, as in what I believe you have now
b) how much various other package infrastructures would differ from the simple interpretation of '*' as standing for "anything coming after this"

**Comment by westy92** [comment]
I got the idea from `gulp-depcheck`.

```js
gulp.task('depcheck', depcheck({
  ignoreDirs: ['lib'],
  ignoreMatches: ['@types/*', 'mocha-bamboo-reporter', 'tslint-microsoft-contrib'],
}));
```

depcheck uses globs: https://github.com/depcheck/depcheck
"`--ignores`: A comma separated array containing package names to ignore. It can be glob expressions. Example, `--ignores="eslint,babel-*".`"
